---
config:
  theme: mc
  look: neo
---
flowchart TD
    main
    main --> RenderHexagonMain
    main --> RandomIntsInRange
    main --> MinForTruchetMode
    main --> MaxForTruchetMode
    main --> GetPointX
    main --> GetPointY

    RenderHexagonMain --> RenderHexagon
    RenderHexagonMain --> TruchetModeIsPattern
    RenderHexagonMain --> PatternRotation
    RenderHexagonMain --> PatternArcIndex

    RenderHexagon --> RenderHexagonBase
    RenderHexagon --> RenderHexagonEdge
    RenderHexagon --> RenderArc
    RenderHexagon --> RenderHexagonLabel

    RenderArc --> RenderRing
    RenderArc --> RenderLine
