---
config:
  theme: mc
  look: neo
---
flowchart TD
    main
    main --> RenderHexagonMain
    main --> RandomIntsInRange
    main --> MinForTruchetMode
    main --> MaxForTruchetMode

    RenderHexagonMain --> RenderHexagon

    RenderHexagon --> RenderHexagonBase
    RenderHexagon --> RenderHexagonEdge
    RenderHexagon --> RenderArc
    RenderHexagon --> RenderHexagonLabel

    RenderArc --> RenderRing
    RenderArc --> RenderLine
